---
title: Ines Mandl Research Foundation
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tylermstrand@gmail.com
description: The Ines Mandle Research Foundation
baseurl: 
url: http://mandlresearch.org/
twitter_username: _tydalwave_
github_username: tstrand
markdown: kramdown
theme: 
